// frontend/src/app/login/page.tsx
"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";

import { AuthCard } from "@/components/auth/auth-card";
import { GoogleSignIn } from "@/components/auth/google-sign-in";
import { authActions } from "@/features/auth/actions/auth-actions";
import { ApiError } from "@/lib/errors/api-error";

function LoginForm() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    setError("");

    if (!email.trim() || !password) {
      setError("Email and password are required.");
      return;
    }

    setLoading(true);

    try {
      await authActions.login({
        email: email.trim(),
        password,
      });

      const next = searchParams.get("next");

      router.replace(next && next.startsWith("/") ? next : "/dashboard");
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message);
      } else if (err instanceof Error) {
        setError(err.message);
      } else {
        setError("Unable to sign in.");
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <AuthCard
      title="Welcome back"
      description="Sign in to continue your conversations."
      footer={
        <p>
          Don&apos;t have an account?{" "}
          <Link
            href="/signup"
            className="font-medium text-foreground hover:underline"
          >
            Create one
          </Link>
        </p>
      }
    >
      <div className="space-y-5">
        <GoogleSignIn
          onSuccess={async (credential) => {
            setError("");
            setLoading(true);

            try {
              await authActions.google(credential);
              router.replace("/dashboard");
            } catch (err) {
              setError(
                err instanceof Error
                  ? err.message
                  : "Google authentication failed.",
              );
            } finally {
              setLoading(false);
            }
          }}
          disabled={loading}
        />

        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t border-border" />
          </div>

          <div className="relative flex justify-center">
            <span className="bg-card px-3 text-xs text-muted-foreground">
              OR
            </span>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label htmlFor="email" className="mb-2 block text-sm font-medium">
              Email address
            </label>

            <input
              id="email"
              type="email"
              autoComplete="email"
              value={email}
              onChange={(event) => setEmail(event.target.value)}
              placeholder="name@company.com"
              disabled={loading}
              className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/20 disabled:opacity-60"
            />
          </div>

          <div>
            <div className="mb-2 flex items-center justify-between">
              <label htmlFor="password" className="text-sm font-medium">
                Password
              </label>

              <Link
                href="/forgot-password"
                className="text-xs text-muted-foreground hover:text-foreground"
              >
                Forgot password?
              </Link>
            </div>

            <input
              id="password"
              type="password"
              autoComplete="current-password"
              value={password}
              onChange={(event) => setPassword(event.target.value)}
              placeholder="••••••••"
              disabled={loading}
              className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/20 disabled:opacity-60"
            />
          </div>

          {error && (
            <p
              role="alert"
              className="rounded-lg border border-destructive/20 bg-destructive/10 px-3 py-2 text-sm text-destructive"
            >
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading}
            className="h-11 w-full rounded-xl bg-primary px-4 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90 disabled:pointer-events-none disabled:opacity-50"
          >
            {loading ? "Signing in…" : "Sign in"}
          </button>
        </form>
      </div>
    </AuthCard>
  );
}

export default function LoginPage() {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-dvh items-center justify-center bg-background">
          <span className="text-sm text-muted-foreground">Loading…</span>
        </div>
      }
    >
      <LoginForm />
    </Suspense>
  );
}

// frontend/src/views/Login.vue
<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { auth_login, auth_google } from '@/api'
import { useUserStore } from '@/stores/userStore'
import { useUIStore } from '@/stores/uiStore'
import { GoogleSignInButton } from 'vue3-google-signin'

const router = useRouter()
const userStore = useUserStore()
const uiStore = useUIStore()

const email = ref('')
const password = ref('')
const error = ref('')

const login = async () => {
  try {
    const data = await auth_login({
      email: email.value,
      password: password.value,
    })

    if (data.detail) {
      uiStore.addToast(typeof data.detail === 'string' ? data.detail : 'Invalid credentials', 'error')
      return
    }

    userStore.setToken(data.access_token)
    userStore.user = data.user
    localStorage.setItem('user', JSON.stringify(data.user))

    uiStore.addToast(`Welcome back, ${data.user.name}!`, 'success')
    router.push('/dashboard')
  } catch (err) {
    uiStore.addToast('Server connection error', 'error')
  }
}

const handleSuccess = async (response) => {
  try {
    alert("SUCCESS TRIGGERED")
    console.log("GOOGLE RESPONSE:", response)
    const { credential } = response
    // Centralized function use karein
    const data = await auth_google(credential)
    
    if (data.access_token) {
      userStore.setToken(data.access_token)
      userStore.user = data.user
      localStorage.setItem('user', JSON.stringify(data.user)) // User info bhi save kar lein sidebar ke liye
      
      uiStore.addToast(`Welcome back, ${data.user.name}!`, 'success')
      router.push('/dashboard')
    } else {
      uiStore.addToast(`Login failed: ${data.detail}!`, 'error')
    }
  } catch (error) {
    uiStore.addToast('Google Auth Error:', 'error')
  }
}
const handleError = () => {
  console.error('Login Failed')
}
</script>

<template>
  <div class="auth-container">
    <div class="auth-card">
      <div class="header">
        <h1>Welcome Back</h1>
        <p>Login to continue your conversations</p>
      </div>

      <GoogleSignInButton
        type="standard"
        shape="rectangular"
        theme="outline"
        size="large"
        @success="handleSuccess"
        @error="handleError"
      ></GoogleSignInButton>

      <div class="form">
        <div class="input-group">
          <label>Email Address</label>
          <input v-model="email" type="email" placeholder="name@company.com" @keyup.enter="login" />
        </div>

        <div class="input-group">
          <label>Password</label>
          <input v-model="password" type="password" placeholder="••••••••" @keyup.enter="login" />
        </div>

        <p class="error-msg" v-if="error">{{ error }}</p>

        <button class="submit-btn" @click="login">Sign In</button>
        <div class="forgot-link">
          <router-link class="link" to="/forgot-password">Forgot Password?</router-link>
        </div>
      </div>

      <div class="footer">
        <p>Don't have an account? <router-link to="/register">Create one</router-link></p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.auth-container {
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: radial-gradient(circle at top right, #1e293b, #0f172a);
  padding: 20px;
}

.auth-card {
  background: rgba(30, 41, 59, 0.7);
  backdrop-filter: blur(10px);
  padding: 40px;
  border-radius: 16px;
  width: 100%;
  max-width: 400px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
}

.header h1 {
  font-size: 24px;
  font-weight: 700;
  margin-bottom: 8px;
  color: #fff;
}
.header p {
  color: #94a3b8;
  font-size: 14px;
  margin-bottom: 30px;
}

.input-group {
  margin-bottom: 20px;
  text-align: left;
}
.input-group label {
  display: block;
  font-size: 13px;
  color: #cbd5e1;
  margin-bottom: 8px;
  font-weight: 500;
}

input {
  width: 100%;
  padding: 12px 16px;
  background: rgba(15, 23, 42, 0.6);
  border: 1px solid #334155;
  border-radius: 8px;
  color: white;
  transition: all 0.2s;
}

input:focus {
  border-color: #3b82f6;
  outline: none;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.2);
}

.submit-btn {
  width: 100%;
  padding: 12px;
  background: #2563eb;
  color: white;
  border: none;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  margin-top: 10px;
  transition:
    transform 0.1s,
    background 0.2s;
}
.submit-btn:hover {
  background: #1d4ed8;
}
.submit-btn:active {
  transform: scale(0.98);
}

.forgot-link { 
  margin-top: 10px;
  font-size: 13px;
  color: white;
}

.link {
  margin-left: 10px;
  color: #94a3b8;
}
.link:hover { 
  color: white;
}

.error-msg {
  color: #f87171;
  font-size: 13px;
  margin-bottom: 15px;
}

.footer {
  margin-top: 25px;
  font-size: 14px;
  color: #94a3b8;
}
.footer a {
  color: #3b82f6;
  text-decoration: none;
  font-weight: 500;
}
.footer a:hover {
  text-decoration: underline;
}
</style>
